create table orders (
    id integer generated by default as identity primary key,
    amount integer
);

create table order_products (
    id integer generated by default as identity primary key,
    order_id integer,
    product_id integer
);

create table products (
    id integer generated by default as identity primary key,
    name varchar(255),
    price integer,
    description varchar(255),
    image_url varchar(255)
);
